sites/hexatrip/protected/controllers/DashboardController.php
<?php

class DashboardController extends Controller {

    /**
     * @return array action filters
     */
    
    public $layout='//layouts/column1';
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'update', 'create', 'delete', 'generate', 'routes', 'upload',
                    'downloadRoutes',
                    'downloadFormat',
                    'loadData',
                    'sendMail',
                    'UserRoutes',
                    'RouteData'
                    
                    
                    ),
                'users' => array('hexatrip'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

//    public function actionIndex() {
//        $this->render('index');
//    }
    
    /**
     * @return Return unique routes for alerts - from-to-date combo unique
     */
    public function actionIndex() {
        $result = array();
        
        
        //get alert count
        $sql = "SELECT COUNT(*) FROM alert where status = 1";
        $result['alert_count'] = Yii::app()->db->createCommand($sql)->queryScalar();
        //get user count
        $sql = "SELECT COUNT(*) FROM tbl_users where status = 1";
        $result['user_count'] = Yii::app()->db->createCommand($sql)->queryScalar();
        //get locations count 
        $sql = "SELECT COUNT(*) FROM location where status = 1";
        $result['location_count'] = Yii::app()->db->createCommand($sql)->queryScalar();
        
        //get email to sent count 
        $sql = "SELECT COUNT(*) FROM alert_status";
        $result['email_count'] = Yii::app()->db->createCommand($sql)->queryScalar();
        //get route count 
        $sql = "select COUNT(*)  from alert
  where alert.status= 1  and 
  location_from<>location_to 
  and date_to > now()
  and date_to < date_add(NOW(),INTERVAL 2 MONTH) 
  group by location_from,location_to";
        $result['route_count'] = count(Yii::app()->db->createCommand($sql)->queryAll());
        
         //get email last sent date 
        $sql = "select DATE_FORMAT(created,'%d%b %y-%h:%s %p') from email_archive order by created desc limit 1";
        $result['email_last_sent'] = Yii::app()->db->createCommand($sql)->queryScalar();
        
        //get Today emails counts 
        $sql = "  select count(*)  from email_archive where created <= NOW() && created >= (NOW() - INTERVAL 1 DAY)";
        $result['email_today'] = Yii::app()->db->createCommand($sql)->queryScalar();
        
        //get weeks emails counts 
        $sql = "  select count(*)  from email_archive where created <= NOW() && created >= (NOW() - INTERVAL 7 DAY)";
        $result['email_week'] = Yii::app()->db->createCommand($sql)->queryScalar();
        
        //get total emails counts 
        $sql = "  select count(*)  from email_archive ";
        $result['email_total'] = Yii::app()->db->createCommand($sql)->queryScalar();
        
         //get Today alert counts 
        $sql = "  select count(*)  from alert where status=1 and created <= NOW() && created >= (NOW() - INTERVAL 1 DAY)";
        $result['alert_today'] = Yii::app()->db->createCommand($sql)->queryScalar();
        
        //get weeks alert counts 
        $sql = "  select count(*)  from alert where status=1 and created <= NOW() && created >= (NOW() - INTERVAL 7 DAY)";
        $result['alert_week'] = Yii::app()->db->createCommand($sql)->queryScalar();
        
         //get Chart data 
        $sql = "  select CONCAT(COUNT(*),'|',DATE(FROM_UNIXTIME(createtime))) as count from tbl_users group by DATE(FROM_UNIXTIME(createtime))";
        $temp = Yii::app()->db->createCommand($sql)->queryAll();
        foreach ($temp as $key => $value) {
            $result['chart_data']['user_chart'][] = explode('|',$value['count']);
        }
        
        //get EMAIL Chart data 
        $sql = "  select CONCAT(COUNT(*),'|',DATE(created)) as count from email_archive group by DATE(created)";
        $temp = Yii::app()->db->createCommand($sql)->queryAll();
        foreach ($temp as $key => $value) {
            $result['chart_data']['email_chart'][] = explode('|',$value['count']);
        }
            
        $this->render('index', array(
            'result'=>$result
                )
        );

    }
    
    public function actionRoutes(){
        $sql = "select * from alert
  where alert.status= 1  and 
  location_from<>location_to 
  and date_to > now()
  and date_to < date_add(NOW(),INTERVAL 2 MONTH) 
  group by location_from,location_to";
        $routes = Yii::app()->db->createCommand($sql)->queryAll();
        $sql = "select * from location";
        $locations = Yii::app()->db->createCommand($sql)->queryAll();

        foreach ($routes as $key => $route) {
            foreach ($locations as $location) {
                if ($location['id'] == $route['location_from']) {
                    $from = array('from_id'=>$location['id'],
                        'from_name'=>$location['name'],
                             'from_desc'=>$location['desc']
                            );
                }
                if ($location['id'] == $route['location_to']) {
                    $to = array('to_id'=>$location['id'],
                        'to_name'=>$location['name'],
                         'to_desc'=>$location['desc']
                            );
                }
            }
            $output[$key] = array_merge($from,$to);
            $output[$key]['id'] = $key+1;
            
        }
        $this->render('routes', array(
            'result' => $output
                )
        );
    }
    
    
    
    
    /**
     * @return returns email table for different type of alert status - uses alert_status table 
     */
    public function actionSendMail() {
        
        //display all alert where email needs to sent to view file 
        
        //if no posted data - first time view - show alert email selection form
        if (!isset($_POST['ApproveButton'])|| !isset($_POST['selectedAlerts']) ){
            //$dataProvider = AlertStatus::model()->findAll();
            $query = "select 
              b.email as alert_email,
              x.id as alert_id,
              x.name as alert_name,
              x.desc as alert_desc,
              z.name as alert_from,
              a.name as alert_to,
              x.date_from as date_from,
              x.date_to as date_to,
              x.created as created,
              x.updated as updated 
              from alert as x 
              join alert_status as y 
              on x.id = y.alert_id
              join location as z on(x.location_from = z.id)
                join location as a on(x.location_to = a.id)
              join tbl_users as b on x.user_id = b.id 
              where x.status = 1
              order by x.created";

            
            $count=count(Yii::app()->db->createCommand($query)->queryAll());
            $dataProvider = new CSqlDataProvider($query, array(
                     'totalItemCount'=>$count,
                'keyField' => 'alert_id',
                'pagination'=>array(
                'pageSize'=>10,
             ),
    ));
            $this->render('send_mail', array(
        'dataProvider' => $dataProvider,
    ));
            return TRUE;
             
        }
        
        
        //some data is posted - prepare and send email for this data
        $changed_alerts = $_POST['selectedAlerts'];
       
        //now looping through each of these matched alerts
        $modelCommon = new Common;
        foreach ($changed_alerts as $key => $changed_alert) {
             
            $mail_data = array();
            //get alert email
            $alert_data  = Alert::model()->findByPK($changed_alert);
            $alert_email =  $modelCommon->alert_user_property($changed_alert, 'email')  ;        
            $alert_user_id = $modelCommon->alert_user_property($changed_alert, 'id')  ;        
            $from = $modelCommon->location_name($alert_data['location_from']);
            $to = $modelCommon->location_name($alert_data['location_to']);
            
            //create notification string for this alerts
            $alert_msg = $this->alert_msg($alert_data,$changed_alert);
            //now generating html array to be passed to view file
            $temp = array();
            $temp['alert_data'] = $alert_data;
            $temp['username'] = $modelCommon->alert_user_property($changed_alert, 'username');
            $temp['msg'] = $alert_msg;
            //pass to send mail function
            $mail_data['model'] =$this->get_mail_html($temp);
//            echo $this->render('/mail/alert_mail',array('model'=>$mail_data['model'] ));
//            die('d');
            //add to email queue
            $mail_data['email_to'] = $alert_email;    
            $mail_data['view_file'] = 'alert_mail';
            $mail_data['subject'] = "Hi ".$temp['username'].",HexaAlert for your route {$from} - {$to} ";
            
           
            if($modelCommon->send_mail($mail_data)){
                //mail sends successful - now delete this record 
                AlertStatus::model()->deleteAll('alert_id=:alertID',array(':alertID'=>$changed_alert));
                //add for tracking purpose
                         $emailArchive = new EmailArchive;
                         $emailArchive->alert_id = $changed_alert;

sites/hexatrip/protected/views/dashboard/index.php
<?php
/* @var $this DashboardController */

$this->breadcrumbs=array(
	'Dashboard',
);
?>
<h1>Admin Dashboard</h1>


<?php 
//$this->widget('zii.widgets.CMenu',array(
//			'items'=>array(
//				array('label'=>'Todays Routes', 'url'=>array('/dashboard/routes')),
//				array('label'=>'Upload Route Data', 'url'=>array('/dashboard/upload')),
//				
//			),
//		)); 
//$this->menu=array(
//	array('label'=>'Load Train Data', 'url'=>array('//tempTrainStatus/loadData ')),
//	array('label'=>'Send Email', 'url'=>array('sendMail')),
//);

?>
<div>
    
    <?php
   
   
    ?>
    
</div>
<!--DASHBOARD BLOCKS-->

<style>
    .block{
        border: 1px solid rgb(221, 213, 213);
padding: 10px;
    }
    .announcement-heading{
        font-size: 30px;
margin: 4px;

    }
    .block-action{
        color:white;
    }
    
</style>
<br/>
<div class="row-fluid">
    <div class="span4"><?php
$array= $result['chart_data']['user_chart'];
//   die(print_r($array));      
$this->widget('jqBarGraph',
array('values'=>$array,
'type'=>'simple',
'width'=>400,
'color1'=>'#122A47',
'color2'=>'#122A47',
'space'=>5,
    'id'=>'graph1',
'title'=>'user Growth'));


?></div>
    
    <div class="span8">
        <div class="row-fluid">
            <div class="span6">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="row-fluid">
                  <ul>
                  <li>
                    <span class="announcement-heading"><?php  echo $result['email_last_sent'] ?></span>
                    <span class="announcement-text1">Email last sent </span>
                    
                  </li>
                    <li>
                    <span class="announcement-heading"><?php  echo $result['email_today'] ?> </span>
                    <span class="announcement-text1">Mails Sent Today</span>
                    
                  </li>
                     <li>
                    <span class="announcement-heading"><?php  echo $result['email_week'] ?></span>
                    <span class="announcement-text1">Mails Sent Last Week</span>
                    
                  </li>
                      <li>
                    <span class="announcement-heading"><?php  echo $result['email_total'] ?></span>
                    <span class="announcement-text1">Total Mails Sent </span>
                    
                  </li>
                     <li>
                    <span class="announcement-heading"><?php  echo $result['alert_today'] ?></span>
                    <span class="announcement-text1">New alerts today</span>
                    
                  </li>
                    <li>
                    <span class="announcement-heading"><?php  echo $result['alert_week'] ?></span>
                    <span class="announcement-text1">New alerts last week </span>
                    
                  </li>
</ul>
                </div>
                </div>
              </div>
           
            </div>
            <div class="span6">
                <ul>
                    <li><p><i class="fa fa-calendar-o fa-2x"></i>  <a class="" href="<?php  echo $this->createUrl('//dashboard/routeData')  ?>" >  View Available Data</a></p></li>
                    <li><p><i class="fa fa-users fa-2x"></i>  <a class="" href="<?php  echo $this->createUrl('//dashboard/userRoutes')  ?>" >View User Alerts</a></p></li>
                </ul>
                <p>
            
           
            </p>
            </div>
          </div>
        </div>
       
<div class="row-fluid">
    
    
          
    
   
     <div class="row-fluid">
            <hr>
      
     </div>
          
         
        </div>
<div class="row-fluid">
          <div class="span4 block">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Routes</h4>
                    <i class="fa fa-calendar fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading"><?php  echo $result['route_count'] ?></p>
                    <p class="announcement-text">Todays  Routes</p>
                     <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//dashboard/routes')  ?>">View Routes</a>
                </p>
                  </div>
                </div>
              </div>
               
           
            </div>
          </div>
          <div class="span4 block">
            <div class="panel panel-warning">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Upload</h4>
                    <i class="fa fa-upload fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading">Upload</p>
                    <p class="announcement-text">Upload file</p>
                      <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//dashboard/upload')  ?>">Upload Train Data</a>
                </p>
                  </div>
                </div>
              </div>
            
            </div>
          </div>
          <div class="span4 block">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Emails</h4>
                    <i class="fa fa-envelope fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading"><?php  echo $result['email_count'] ?></p>
                    <p class="announcement-text">Pending Email(s)</p>
                     <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//dashboard/sendMail')  ?>">Send Emails</a>
                </p>
                  </div>
                </div>
              </div>
           
            </div>
          </div>
         
        </div>
<div class="row-fluid">
    <br/>
</div>
<div class="row-fluid">
          <div class="span4 block">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Alerts</h4>
                    <i class="fa fa-bell fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading"><?php  echo $result['alert_count'] ?></p>
                    <p class="announcement-text">Active Alerts</p>
                    <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//alert/admin')  ?>"> Manage Alerts</a>
                </p>
                  </div>
                </div>
              </div>
           
            </div>
          </div>
          <div class="span4 block">
            <div class="panel panel-warning">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Users</h4>
                    <i class="fa fa-group fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading"><?php  echo $result['user_count'] ?></p>
                    <p class="announcement-text">Active Users</p>
                      <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//user/admin')  ?>"> Manage Users</a>
                </p>
                  </div>
                </div>
              </div>
          
            </div>
          </div>
          <div class="span4 block">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Locations</h4>
                    <i class="fa fa-flag fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading"><?php  echo $result['location_count'] ?></p>
                    <p class="announcement-text">Active Locations</p>
                      <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//location/admin')  ?>"> Manage Locations</a>
                </p>
                  </div>
                </div>
              </div>
        
            </div>
          </div>
         
        </div>
<!--
<div class="row-fluid">
    <br/>
</div>
<div class="row-fluid">
          <div class="span4 block">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>User Routes</h4>
                    <i class="fa fa-users fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    
                    <p class="announcement-text">User`s Alerts</p>
                    <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//dashboard/userRoutes')  ?>"> View User Alerts</a>
                </p>
                  </div>
                </div>
              </div>
           
            </div>
          </div>
          <div class="span4 block">
            <div class="panel panel-warning">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Users</h4>
                    <i class="fa fa-group fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading"><?php  echo $result['user_count'] ?></p>
                    <p class="announcement-text">Active Users</p>
                      <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//dashboard/routeData')  ?>"> Manage Users</a>
                </p>
                  </div>
                </div>
              </div>
          
            </div>
          </div>
          <div class="span4 block">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <div class="row-fluid">
                  <div class="span6">
                      <h4>Locations</h4>
                    <i class="fa fa-flag fa-5x"></i>
                  </div>
                  <div class="span6 text-right">
                    <p class="announcement-heading"><?php  echo $result['location_count'] ?></p>
                    <p class="announcement-text">Active Locations</p>
                      <p >
                    <a class="btn btn-primary block-action" href="<?php  echo $this->createUrl('//location/admin')  ?>"> Manage Locations</a>
                </p>
                  </div>
                </div>
              </div>
        
            </div>
          </div>
         
        </div>-->

sites/hexatrip/protected/views/dashboard/routes.php
<?php
/* @var $this DashboardController */

$this->breadcrumbs=array(
	'Dashboard',
);

$this->menu=array(
	array('label'=>'Load Train Data', 'url'=>array('//tempTrainStatus/loadData ')),
	array('label'=>'Send Email', 'url'=>array('sendMail')),
);
?>
<h1>Unique Routes</h1>
<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Download Routes as csv', 'url'=>array('/dashboard/downloadroutes')),
//				array('label'=>'Upload Route Data', 'url'=>array('/dashboard/upload')),

			),
		)); 

//main table for routes display 

//$invoiceItems =  array(
//  [0]=>array('name'=>'x','price'=>230),  
//    [1]=>array('name'=>'x','price'=>230),
//);
//$invoiceItemsDataProvider = new CArrayDataProvider($invoiceItems);
//$this->widget('zii.widgets.grid.CGridView', array(
//               'dataProvider'=>$invoiceItemsDataProvider,
//              ));

//$data  = new CArrayDataProvider($result);
//die(print_r($data));
//$this->widget('zii.widgets.grid.CGridView', array(
//    'id'=>'',
//    'dataProvider'=>$data->rawData,
//    
//));


?>

<?php
//$arr=array(
//array('id'=>1,'name'=>"jack","age"=>10,"sex"=>"male"),
//array('id'=>2,'name'=>"jill","age"=>8,"sex"=>"female"),
//array('id'=>3,'name'=>"jhon","age"=>6,"sex"=>"male"),
//array('id'=>4,'name'=>"jerry","age"=>4,"sex"=>"male"),
//
//);
$arr =  $result;

$dataProvider=new CArrayDataProvider($arr,array(
'sort'=>array('attributes'=>array('from_id','from_name','to_id','to_name'),),
'pagination'=>false

));
?>
<div class="row-fluid">
    <div class="span12">
        <?php $this->widget('zii.widgets.grid.CGridView', array(
        'id'=>'post-grid1',
         'itemsCssClass' => 'table',
'htmlOptions' => array('class' => 'table  table-bordered table-hover'),
        'dataProvider'=>$dataProvider,
        'columns'=>array(
            array(
                'name'=>'id',
                'value'=>'$data["id"]',
                ),
                array(
                'name'=>'From ID',
                'value'=>'$data["from_id"]',
                ),
                array(
                'name'=>'From Name',
                'value'=>'$data["from_name"]',
                ),
                array(
                'name'=>'From Desc',
                'value'=>'$data["from_desc"]',
                ),
                array(
                'name'=>'To ID',
                'value'=>'$data["to_id"]',
                ),
                array(
                'name'=>'To Name',
                'value'=>'$data["to_name"]',
                ),
            array(
                'name'=>'To Desc',
                'value'=>'$data["to_desc"]',
        ),
        ),
)); ?>
    </div>
</div>


<div>
    
    <?php
//    if(isset($result)){
//        $htm = '<table class="table  table-striped  table-bordered table-hover table-condensed"><tr>
//            <th>SNo</th>
//            <th>From ID</th>
//            <th>From</th>
//            <th>To ID</th>
//            <th>To</th>
//            </tr>';
//        foreach ($result as $key => $value) {
//    
//            $htm.='<tr>';
//            $htm.='<td>'.($key+1).'</td>';
//            $htm.='<td>'.$value['from']['id'].'</td><td>'.
//                    $value['from']['name'].'</td><td>'.
//                    $value['to']['id'].'</td><td>'.
//                    $value['to']['name'].'</td>';
//            $htm.='</tr>';
//}
//$htm.= '</table>';   
//echo $htm;    
//        
//    }
    
   
    ?>
     
</div>

sites/hexatrip/protected/views/dashboard/send_mail.php
<h1>Send Emails </h1>
<div class="row-fluid">
    <div>
        <br/>
    </div>
    
    
    <?php  if(isset($dataProvider)){  ?>
    
    <?php echo CHtml::beginForm(); ?>

<?php 
//$columns = array_keys($dataProvider->metaData->columns);
//$columns[array_search('alert_id', $columns)] = 
//        array(
//        'name'=>'Alert ID',             'value'=>'CHtml::checkBox("selectedAlerts[]",null,array("value"=>$data->alert_id,"id"=>"cid_".$data->id))',
//        'type'=>'raw',
//        'htmlOptions'=>array('width'=>5),
//        //'visible'=>false,
//        );
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>$dataProvider,
    'selectableRows' => 20,
    'columns'=>array(
    array(
        'name'=>'#',
        'type'=>'raw',
        'value'=>'CHtml::checkBox("selectedAlerts[]",null,array("value"=>$data["alert_id"],"id"=>"cid_".$data["alert_id"]))'
    ),
     array(
        'name'=>'Alert ID',
        'value'=>'$data["alert_id"]'
    ),
         array(
        'name'=>'Alert Email',
        'value'=>'$data["alert_email"]'
    ),
        array(
        'name'=>'Alert Name',
        'value'=>'$data["alert_name"]'
    ),
         array(
        'name'=>'Alert Desc',
        'value'=>'$data["alert_desc"]'
    ),
        array(
        'name'=>'Alert From',
        'value'=>'$data["alert_from"]'
    ),
          array(
        'name'=>'Alert To',
        'value'=>'$data["alert_to"]'
    ),
        array(
        'name'=>'Date From',
        'value'=>'$data["date_from"]'
    ),
         array(
        'name'=>'Date To',
        'value'=>'$data["date_to"]'
    ),
        array(
        'name'=>'Created',
        'value'=>'$data["created"]'
    ),
          array(
        'name'=>'Updated',
        'value'=>'$data["updated"]'
    ),
   
        )
    
   
));
?>

<div>
<?php echo CHtml::submitButton('Send Emails to Selected Alerts', array('name' => 'ApproveButton','class'=>'btn btn-primary btn-large')); ?>
<?php 
//echo CHtml::submitButton('Delete', 
//array('name' => 'DeleteButton',
//'confirm' => 'Are you sure you want to permanently delete these comments?'));
?>
</div>

<?php echo CHtml::endForm(); ?>
    
    <?php } ?>
    
<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

if(FALSE){ 
    
    
    
    ?>
    
     <table class="table  table-striped  table-bordered table-hover">
         <thead>
     <tr>
       <th>Alert ID</th>
       <th>Email</th>
       <th>User</th>
       <th>Location From</th>
       <th>Location to</th>
        <th>Date From</th>
       <th>Date to</th>
       <th>User Settings</th>       
       <th>What changed</th>
     </tr>
         </thead>
          <tbody>
     <? foreach ($result as $row) : ?>
     <tr>
       <td><? echo $row['alert_data']['alert_unique_id']; ?></td>
       <td><? echo $row['alert_data']['email']; ?></td>
       <td><? echo $row['alert_data']['username']; ?></td>
       <td><? echo $row['alert_data']['location_from']; ?></td>
       <td><? echo $row['alert_data']['location_to']; ?></td>
       <td><? echo $row['alert_data']['date_from']; ?></td>
       <td><? echo $row['alert_data']['date_to']; ?></td>
       <td><? echo 
       'Train:'.$row['alert_data']['train']. '<br/>'.
        'Bus:'.$row['alert_data']['bus'].'<br/>'.
         'Flight:'.$row['alert_data']['flight']; 
       
       ?></td>
      
       <td><? echo implode('<br/>',$row['notification_data']); ?></td>
      
     </tr>
     <? endforeach; ?>
          </tbody>
   </table>

<?php  
} 
?>

</div>

sites/hexatrip/protected/views/dashboard/upload.php
<div class="content">
    <h1>Upload File</h1>
<div class="form well well-small">


<?php if($uploaded):?>
    
    
<p>File was uploaded. Check <?php echo $dir?>.</p>
<?php endif ?>
<?php echo CHtml::beginForm('','post',array
('enctype'=>'multipart/form-data'))?>



<div class="control-group">
              <label class="control-label" for="inputEmail">File</label>
              <div class="controls">
                <?php echo CHtml::error($model, 'file')?>
<?php echo CHtml::activeFileField($model, 'file')?>

              </div>
            </div>

<div class="control-group">
              <label class="control-label" for="inputEmail">Type:</label>
              <div class="controls">
                <select name="type" >
<option value="TRAIN">Train</option> 
<option value="FLIGHT">Flight</option> 
</select>
              </div>
            </div>
<?php echo CHtml::submitButton('Upload',array('class'=>'btn btn-primary btn-large')); ?>

          
<?php echo CHtml::endForm()?>

sites/hexatrip/protected/views/dashboard/user_routes.php
<?php
/* @var $this DashboardController */

$this->breadcrumbs=array(
	'Dashboard',
);

$this->menu=array(
	array('label'=>'Load Train Data', 'url'=>array('//tempTrainStatus/loadData ')),
	array('label'=>'Send Email', 'url'=>array('sendMail')),
);
?>
<h1>User Routes</h1>

<div class="row-fluid">
    <div class="span12">
        <?php $this->widget('zii.widgets.grid.CGridView', array(
'id'=>'students-grid',
'dataProvider'=> $result, 
)); ?>
    </div>
</div>


<div>
    
    
     
</div>